### ISSUE TITLE
测试代码可能存在问题

### ISSUE THREAD

**Issue by hlm2859506** [udacity/JavaBasics-BetaTesting-CN#6]
## 课程导航+链接
课程3：控制流和条件语句> 6.汽车雨刮器
https://classroom.udacity.com/nanodegrees/nd301-cn-basic/parts/7fb588b8-481c-4c93-9e70-34f6abf4e32e/modules/13ff4794-8d63-4fd5-a29c-458f7e2f9c39/lessons/adacacb0-a412-4307-a56e-b2d0e9703ce2/concepts/5124da5d-d4e0-4156-962c-89f5c4ced56c

## 截图
![bug1](https://user-images.githubusercontent.com/36024694/35972922-7efe6e96-0d0e-11e8-8922-ab70176a0f7b.png)

## 具体描述
将下方答案输入至题目并提交，出现了错误
错误内容为：
Traceback (most recent call last): File "/base/data/home/apps/s~udacityu/dangerzone-2108.407492534069004009/src/models/content.py", line 1123, in evaluate graded_result = yield self.evaluator.process(submission, processed_results) File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 430, in _help_tasklet_along value = gen.send(val) File "/base/data/home/apps/s~udacityu/dangerzone-2108.407492534069004009/src/models/evaluation.py", line 97, in process result = yield self.evaluate(submission, processed_results) File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 1057, in tasklet_wrapper result = func(*args, **kwds) File "/base/data/home/apps/s~udacityu/dangerzone-2108.407492534069004009/src/models/evaluation.py", line 1073, in evaluate custom_bin_codes or ['comment::%s' % comment[:MAX_BIN_CODE_SIZE]]))) File "/base/data/home/apps/s~udacityu/dangerzone-2108.407492534069004009/src/models/evaluation.py", line 396, in __init__ super(SubmissionEvaluation, self).__init__(*args, **kwargs) File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 2947, in __init__ self._set_attributes(kwds) File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 2993, in _set_attributes prop._set_value(self, value) File "/base/data/home/apps/s~udacityu/dangerzone-2108.407492534069004009/src/core/warden.py", line 602, in _guarded_set_value _original_set_value(self, entity, value) File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1145, in _set_value value = self._do_validate(value) File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1092, in _do_validate value = self._call_shallow_validation(value) File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1284, in _call_shallow_validation return call(value) File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1331, in call newvalue = method(self, value) File "/base/alloc/tmpfs/dynamic_runtimes/python27/a7637d5531ec9deb_unzipped/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1596, in _validate (value,)) BadValueError: Expected bool, got u''

**Comment by ghost** [comment]
起始代码文件名应该是`Starter.java`，之前写成了`Start.java`。现在应该正常了。
